"""
mcp-forge evaluate — Évaluation automatique d'un serveur MCP généré.
Usage : mcp-forge evaluate <server.py> [options]
"""
from __future__ import annotations

import json
import os
import sys
import textwrap  # utilisé dans _SYSTEM_PROMPT
from pathlib import Path

import httpx
from rich.console import Console
from rich.panel import Panel
from rich.table import Table
from rich import box
from rich.text import Text

from mcp_forge.groq_models import resolve_groq_model

_console = Console()
# 1500 s'est avéré trop court pour un rapport complet (6 scores + points forts +
# bugs détaillés + verdict) dès que le modèle est un peu verbeux — observé en
# production sur des sources CLI/GraphQL/website (json.loads plantait avec
# "Expecting value"/"Expecting ',' delimiter", la réponse étant coupée en
# plein milieu par le fournisseur). Les générations OpenAPI passaient par
# chance sous la barre des 1500 tokens plus souvent que les autres sources.
_MAX_TOKENS = 3000
_CODE_CHAR_LIMIT = 200_000

# Providers supportés — détectés automatiquement depuis les variables d'environnement.
# Ordre de priorité : Anthropic > Groq > OpenAI > Mistral > LLM_BASE_URL (Ollama/LM Studio...)
_PROVIDERS = [
    {
        "name": "Anthropic",
        "env_key": "ANTHROPIC_API_KEY",
        "url": "https://api.anthropic.com/v1/messages",
        "model": "claude-sonnet-4-6",
        "format": "anthropic",
    },
    {
        "name": "Groq",
        "env_key": "GROQ_API_KEY",
        "url": "https://api.groq.com/openai/v1/chat/completions",
        "model": "llama-3.3-70b-versatile",
        "format": "openai",
    },
    {
        "name": "OpenAI",
        "env_key": "OPENAI_API_KEY",
        "url": "https://api.openai.com/v1/chat/completions",
        "model": "gpt-4o-mini",
        "format": "openai",
    },
    {
        "name": "Mistral",
        "env_key": "MISTRAL_API_KEY",
        "url": "https://api.mistral.ai/v1/chat/completions",
        "model": "mistral-small-latest",
        "format": "openai",
    },
]

CRITERIA = {
    "structure":  "Code structure (readability, organisation, FastMCP idioms)",
    "coverage":   "Endpoint coverage (all tools present and correct)",
    "auth":       "Auth & security (env vars, headers, no hardcoded secrets)",
    "docs":       "Description quality (docstrings, tool names, Args)",
    "fidelity":   "Spec fidelity (types, body vs params, path params)",
    "robustness": "Robustness (timeout, error handling, default values)",
}

# Schéma JSON du rapport, utilisé pour forcer une sortie structurée côté
# fournisseur (Anthropic tool-use, Groq/OpenAI response_format=json_object)
# plutôt que de faire confiance à du texte libre. Root cause du bug observé
# en prod : un modèle qui génère lui-même le JSON en texte libre échappe mal
# les guillemets à l'intérieur d'une description (fréquent sur du contenu
# CLI/GraphQL/website, ex: `git commit -m "message"`), ce qui casse
# json.loads en plein milieu de la réponse — jamais une histoire de longueur
# tronquée malgré les apparences.
_REPORT_SCHEMA = {
    "type": "object",
    "properties": {
        "score_global": {"type": "number"},
        "scores_par_critere": {
            "type": "object",
            "properties": {k: {"type": "number"} for k in CRITERIA},
            "required": list(CRITERIA.keys()),
        },
        "points_forts": {"type": "array", "items": {"type": "string"}},
        "bugs_critiques": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "description": {"type": "string"},
                    "ligne": {"type": ["integer", "null"]},
                    "severite": {"type": "string", "enum": ["bloquant", "majeur", "mineur"]},
                },
                "required": ["description", "severite"],
            },
        },
        "ameliorations_prioritaires": {"type": "array", "items": {"type": "string"}},
        "verdict_beta": {"type": "string"},
    },
    "required": [
        "score_global", "scores_par_critere", "points_forts",
        "bugs_critiques", "ameliorations_prioritaires", "verdict_beta",
    ],
}

_SYSTEM_PROMPT = textwrap.dedent("""
    You are an expert in MCP (Model Context Protocol) and Python code quality.
    You evaluate MCP servers automatically generated by mcp-forge (a VulcAi tool, beta version).
    Your role is to provide a structured, honest and actionable evaluation.

    IMPORTANT CONTEXT — read before evaluating:
    1. HTTP methods (GET, POST, PUT, PATCH, DELETE) are extracted directly from the OpenAPI/Swagger spec.
       Do NOT flag an HTTP method as wrong unless the code uses a different method than what is declared
       in the function name or docstring. The spec is the ground truth — trust it.
    1b. The choice of `params=` (query string), `json=`/`data=` (request body — JSON vs
       form-urlencoded) and header injection (values merged into the `httpx.Client(headers=...)`
       call, e.g. via `_extra_headers`) was derived deterministically from the source spec's
       parameter locations (`in: query/path/header/body`/`formData`), not guessed. Trust it as
       ground truth exactly like the HTTP method: do NOT suggest switching `params=` to
       `data=`/`json=` or vice versa, and do NOT suggest moving a parameter already merged into
       headers to a query string or body, purely based on generic REST conventions (e.g. "a POST
       endpoint should use a body"). Only flag it if the code is internally inconsistent — e.g. the
       same parameter is referenced in both `params=` and `json=` for the same call, or a value the
       code itself declares as a header is also duplicated into `params=`.
    2. This is an MCP server: tools receive text/JSON values from an LLM, never raw binary data.
       File upload parameters are correctly represented as `file_path: str` (the caller passes a local path).
       Do NOT flag file_path parameters or `open(file_path, "rb")` patterns as incorrect.
    3. The code is auto-generated from a spec. Patterns like `{k: v for k, v in {...}.items() if v is not None}`
       are intentional and correct — do not flag them as style issues.
    4. Severity rules — be strict:
       - "bloquant": code that will raise an exception or crash at runtime (SyntaxError, NameError, etc.)
       - "majeur": incorrect API behavior (wrong endpoint, missing required param, broken auth)
       - "mineur": style, readability, or minor improvements only
       Only report bugs you are confident about. Prefer fewer, accurate bugs over many speculative ones.
    5. `_BEARER_TOKEN = os.getenv("BEARER_TOKEN", "")` reads from an environment variable — this is NOT
       a hardcoded secret. Do NOT flag it as a security vulnerability.
    6. Checks like `if email is None or email == "": return "Error: ..."` ARE valid input validation for
       an MCP server. Do NOT flag them as missing or insufficient validation.
    7. The `if __name__ == "__main__":` block implements a complete OAuth 2.0 Authorization Code + PKCE
       server (login page, /oauth/authorize, /oauth/token, PKCE S256 verification, CORS, rate limiting).
       Do NOT suggest "adding OAuth" or "using a more secure authentication method" — it is already there.
    8. Explicit timeouts (`timeout=30`, `timeout=120`) are correct and intentional. Do NOT flag them as
       potential timeout issues or suggest changing them.
    9. `_request_token: ContextVar[str]` is a standard per-async-task token mechanism. It is NOT a
       security vulnerability and NOT shared between users.
    10. If `_check_rate_limit` is present in the code, the OAuth endpoints already have rate limiting —
        do NOT flag it as missing. If it is absent, you may flag it as a minor improvement.
    11. `_verify_pkce` wraps `code_verifier.encode("ascii")` in a try/except — this is correct and safe.
        Do NOT flag it as a security vulnerability.

    Respond ONLY with valid JSON, no markdown, no text before or after.
    Expected exact structure:

    {
      "score_global": <float 0-10>,
      "scores_par_critere": {
        "structure":  <float 0-10>,
        "coverage":   <float 0-10>,
        "auth":       <float 0-10>,
        "docs":       <float 0-10>,
        "fidelity":   <float 0-10>,
        "robustness": <float 0-10>
      },
      "points_forts": ["...", "..."],
      "bugs_critiques": [
        {"description": "...", "ligne": <int or null>, "severite": "bloquant|majeur|mineur"}
      ],
      "ameliorations_prioritaires": ["...", "..."],
      "verdict_beta": "..."
    }
""").strip()




# ---------------------------------------------------------------------------
# Core
# ---------------------------------------------------------------------------

def _build_prompt(code: str, context: str | None) -> str:
    lines = []
    if context:
        lines.append(f"Context: {context}\n")
    lines.append("Server code to evaluate:\n```python")
    lines.append(code[:_CODE_CHAR_LIMIT])
    if len(code) > _CODE_CHAR_LIMIT:
        lines.append(f"... [{len(code) - _CODE_CHAR_LIMIT} chars truncated]")
    lines.append("```")
    lines.append("\nEvaluate this server and return only the requested JSON.")
    return "\n".join(lines)


def _detect_provider(forced_key: str | None) -> tuple[dict, str]:
    """Détecte le premier provider disponible dans l'environnement.

    Si forced_key est fourni, on l'utilise avec Anthropic (comportement --api-key).
    Retourne (provider_config, api_key) ou lève RuntimeError si aucun provider trouvé.
    """
    if forced_key:
        return _PROVIDERS[0], forced_key  # Anthropic avec clé explicite

    # LLM_BASE_URL en dernier recours (Ollama, LM Studio...)
    llm_base_url = os.getenv("LLM_BASE_URL", "")
    llm_model = os.getenv("LLM_MODEL", "llama3.2")

    for provider in _PROVIDERS:
        key = os.getenv(provider["env_key"], "")
        if key:
            if provider["name"] == "Groq":
                provider = {**provider, "model": resolve_groq_model(key)}
            return provider, key

    if llm_base_url:
        return {
            "name": f"OpenAI-compat ({llm_model})",
            "env_key": "LLM_BASE_URL",
            "url": llm_base_url,
            "model": llm_model,
            "format": "openai",
        }, "local"

    raise RuntimeError(
        "No LLM API key found. Set one of: ANTHROPIC_API_KEY, GROQ_API_KEY, OPENAI_API_KEY, or LLM_BASE_URL"
    )


_EVAL_TOOL_NAME = "submit_evaluation"


def _call_llm(code: str, context: str | None, provider: dict, api_key: str) -> dict:
    """Appelle le LLM et renvoie le rapport parsé.

    Force une sortie structurée côté fournisseur plutôt que de faire
    confiance à du JSON en texte libre : Anthropic via tool-use (le rapport
    arrive déjà parsé, correctement échappé, dans `content[].input`), les
    providers OpenAI-compatibles (Groq, OpenAI...) via
    `response_format: json_object`. Root cause du bug évité : un modèle qui
    écrit lui-même son JSON en texte libre échappe parfois mal un guillemet
    à l'intérieur d'une description (fréquent sur du contenu CLI/GraphQL/
    website, ex: `git commit -m "message"`), ce qui casse `json.loads` en
    plein milieu de la réponse — la sortie contrainte élimine cette classe
    d'erreur à la source.
    """
    prompt = _build_prompt(code, context)

    if provider["format"] == "anthropic":
        payload = {
            "model": provider["model"],
            "max_tokens": _MAX_TOKENS,
            "system": _SYSTEM_PROMPT,
            "messages": [{"role": "user", "content": prompt}],
            "tools": [{
                "name": _EVAL_TOOL_NAME,
                "description": "Submit the structured MCP server evaluation report.",
                "input_schema": _REPORT_SCHEMA,
            }],
            "tool_choice": {"type": "tool", "name": _EVAL_TOOL_NAME},
        }
        headers = {
            "x-api-key": api_key,
            "anthropic-version": "2023-06-01",
            "content-type": "application/json",
        }
    else:  # openai-compatible (Groq, OpenAI, Ollama...)
        payload = {
            "model": provider["model"],
            "max_tokens": _MAX_TOKENS,
            "messages": [
                {"role": "system", "content": _SYSTEM_PROMPT},
                {"role": "user", "content": prompt},
            ],
            "response_format": {"type": "json_object"},
        }
        headers = {
            "Authorization": f"Bearer {api_key}",
            "content-type": "application/json",
        }

    with httpx.Client(timeout=60) as client:
        response = client.post(provider["url"], json=payload, headers=headers)

    if not response.is_success:
        raise RuntimeError(f"{provider['name']} API — HTTP {response.status_code}: {response.text}")

    data = response.json()
    if provider["format"] == "anthropic":
        tool_use = next(
            (block for block in data.get("content", []) if block.get("type") == "tool_use"),
            None,
        )
        if tool_use is None:
            raise RuntimeError(f"{provider['name']} did not return a tool_use block")
        return _normalize_report(tool_use["input"])

    text = data["choices"][0]["message"]["content"].strip()
    if text.startswith("```"):
        text = "\n".join(
            line for line in text.splitlines()
            if not line.strip().startswith("```")
        ).strip()

    return _normalize_report(json.loads(text))


_LIST_FIELDS = ("points_forts", "bugs_critiques", "ameliorations_prioritaires")


def _normalize_report(report: dict) -> dict:
    """Corrige les champs censés être des listes mais renvoyés en chaîne.

    Le mode `json_object` de Groq garantit du JSON top-level valide mais pas
    le respect du schéma imbriqué qu'on lui demande : le modèle renvoie
    parfois un tableau tout entier ré-encodé en une seule chaîne JSON (ex:
    `"bugs_critiques": "[{\\"description\\": ...}]"` au lieu d'un vrai
    tableau). Sans ce filet, chaque caractère de la chaîne finit itéré comme
    un faux "bug" d'un caractère dans render_report()/refine.py.
    """
    for field in _LIST_FIELDS:
        value = report.get(field)
        if isinstance(value, str):
            try:
                parsed = json.loads(value)
            except json.JSONDecodeError:
                parsed = [value] if value else []
            report[field] = parsed if isinstance(parsed, list) else [parsed]
    return report


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------

def _score_style(score: float) -> str:
    if score >= 7.5:
        return "bold green"
    if score >= 5.0:
        return "bold yellow"
    return "bold red"


def _score_bar(score: float, width: int = 20) -> Text:
    filled = round(score / 10 * width)
    style = _score_style(score)
    t = Text()
    t.append(f"{score:.1f}/10", style=style)
    t.append("  ")
    t.append("█" * filled, style=style)
    t.append("░" * (width - filled), style="dim")
    return t


def _severity_style(sev: str) -> tuple[str, str]:
    mapping = {
        "bloquant": ("BLOCKING", "bold red"),
        "majeur":   ("MAJOR",    "bold yellow"),
        "mineur":   ("minor",    "dim"),
    }
    return mapping.get(sev.lower(), (sev.upper(), "dim"))


def render_report(result: dict, server_path: str, output_json: bool = False) -> None:
    if output_json:
        print(json.dumps(result, ensure_ascii=False, indent=2))
        return

    score = result.get("score_global", 0)

    # Header
    _console.print()
    _console.print(Panel(
        f"[dim]{server_path}[/dim]",
        title="[bold cyan]mcp-forge evaluate[/bold cyan]",
        border_style="cyan",
        padding=(0, 2),
    ))

    # Global score
    _console.print()
    t = Text("  Global score   ")
    t.append_text(_score_bar(score))
    _console.print(t)
    _console.print()

    # Per criterion table
    table = Table(box=box.SIMPLE, show_header=True, header_style="dim", padding=(0, 2))
    table.add_column("Criterion", style="dim", min_width=45)
    table.add_column("Score", justify="right")
    for key, label in CRITERIA.items():
        s = result.get("scores_par_critere", {}).get(key, 0)
        score_text = Text(f"{s:.1f}/10", style=_score_style(s))
        table.add_row(label, score_text)
    _console.print(table)

    # Strengths
    pts = result.get("points_forts", [])
    if pts:
        _console.rule(style="dim")
        _console.print("\n[bold]  Strengths[/bold]")
        for p in pts:
            _console.print(f"  [green]✓[/green]  {p}")

    # Bugs
    bugs = result.get("bugs_critiques", [])
    if bugs:
        _console.rule(style="dim")
        _console.print("\n[bold]  Bugs detected[/bold]")
        for b in bugs:
            # Groq's json_object mode only guarantees valid JSON, not that
            # each array item matches the object schema we asked for — it
            # sometimes returns a bare string instead of {description, ligne,
            # severite}. Fall back gracefully instead of crashing the render.
            if not isinstance(b, dict):
                b = {"description": str(b)}
            label, style = _severity_style(b.get("severite", ""))
            ligne = b.get("ligne")
            loc = f" line {ligne}" if ligne else ""
            _console.print(f"  [{style}][{label}][/{style}][dim]{loc}[/dim]  {b.get('description', '')}")

    # Improvements
    amelios = result.get("ameliorations_prioritaires", [])
    if amelios:
        _console.rule(style="dim")
        _console.print("\n[bold]  Priority improvements[/bold]")
        for i, a in enumerate(amelios, 1):
            _console.print(f"  [dim]{i}.[/dim]  {a}")

    # Verdict
    verdict = result.get("verdict_beta", "")
    if verdict:
        _console.rule(style="dim")
        _console.print(Panel(
            verdict,
            title="[bold]Beta verdict[/bold]",
            border_style="dim",
            padding=(0, 2),
        ))

    _console.print()


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def evaluate_code(code: str, api_key: str | None = None, groq_key: str | None = None) -> dict:
    """Évalue un serveur MCP depuis son code source (string). Utilisé par l'API.

    Priorité : Anthropic (api_key) → Groq (groq_key) → détection auto depuis env.

    Contrairement à l'enrichissement/refine (où Groq est prioritaire pour le coût),
    l'éval essaie Anthropic en premier ici : le tool-use forcé (voir `_call_llm`)
    garantit une sortie déjà parsée et correctement échappée. Le mode
    `response_format=json_object` de Groq, lui, n'a pas éliminé en pratique les
    erreurs de JSON mal formé observées en production (guillemets non échappés
    dans une description générée en texte libre, ex: du contenu CLI/GraphQL/
    website) — voir tests/test_evaluate_structured_output.py.
    """
    if api_key:
        try:
            return _call_llm(code, None, _PROVIDERS[0], api_key)
        except Exception:
            if groq_key:
                groq_provider = {**next(p for p in _PROVIDERS if p["name"] == "Groq"), "model": resolve_groq_model(groq_key)}
                return _call_llm(code, None, groq_provider, groq_key)
            raise
    if groq_key:
        groq_provider = {**next(p for p in _PROVIDERS if p["name"] == "Groq"), "model": resolve_groq_model(groq_key)}
        return _call_llm(code, None, groq_provider, groq_key)
    provider, key = _detect_provider(api_key)
    return _call_llm(code, None, provider, key)


def evaluate(
    server_path: str,
    context: str | None = None,
    output_json: bool = False,
    api_key: str | None = None,
    save: str | None = None,
) -> dict:
    """
    Évalue un serveur MCP généré par mcp-forge.

    Le provider LLM est détecté automatiquement depuis les variables d'environnement
    (ANTHROPIC_API_KEY → GROQ_API_KEY → OPENAI_API_KEY → LLM_BASE_URL).

    Args:
        server_path: Chemin vers le server.py à évaluer.
        context:     Contexte additionnel transmis au LLM.
        output_json: Si True, affiche uniquement le JSON brut.
        api_key:     Clé API explicite (force Anthropic, bypass détection auto).
        save:        Chemin optionnel pour sauvegarder le rapport JSON.
    """
    try:
        provider, key = _detect_provider(api_key)
    except RuntimeError as exc:
        _console.print(f"[bold red]Error:[/bold red] {exc}")
        sys.exit(1)

    path = Path(server_path)
    if not path.exists():
        _console.print(f"[bold red]Error:[/bold red] file not found — {server_path}")
        sys.exit(1)

    code = path.read_text(encoding="utf-8")

    try:
        if not output_json:
            with _console.status(
                f"[dim]Analysing with [bold]{provider['name']}[/bold] ({provider['model']})… {len(code)} chars[/dim]"
            ):
                result = _call_llm(code, context, provider, key)
        else:
            result = _call_llm(code, context, provider, key)
    except json.JSONDecodeError as exc:
        _console.print(f"[bold red]Error:[/bold red] LLM response is not valid JSON — {exc}")
        sys.exit(1)
    except RuntimeError as exc:
        _console.print(f"[bold red]Error:[/bold red] {exc}")
        sys.exit(1)

    render_report(result, server_path, output_json=output_json)

    if save:
        Path(save).write_text(json.dumps(result, ensure_ascii=False, indent=2), encoding="utf-8")
        if not output_json:
            _console.print(f"[dim]  Report saved → {save}[/dim]")

    return result
